// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: alpv_ws1112/ub1/webradio/proto/packetprotos.proto

package alpv_ws1112.ub1.webradio.proto;

public final class PacketProtos {
  private PacketProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface MessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional .alpv_ws1112.ub1.webradio.proto.Message.Chat chat = 1;
    boolean hasChat();
    alpv_ws1112.ub1.webradio.proto.PacketProtos.Message.Chat getChat();
    alpv_ws1112.ub1.webradio.proto.PacketProtos.Message.ChatOrBuilder getChatOrBuilder();
    
    // optional string format = 2;
    boolean hasFormat();
    String getFormat();
    
    // optional bytes data = 3;
    boolean hasData();
    com.google.protobuf.ByteString getData();
  }
  public static final class Message extends
      com.google.protobuf.GeneratedMessage
      implements MessageOrBuilder {
    // Use Message.newBuilder() to construct.
    private Message(Builder builder) {
      super(builder);
    }
    private Message(boolean noInit) {}
    
    private static final Message defaultInstance;
    public static Message getDefaultInstance() {
      return defaultInstance;
    }
    
    public Message getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return alpv_ws1112.ub1.webradio.proto.PacketProtos.internal_static_alpv_ws1112_ub1_webradio_proto_Message_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return alpv_ws1112.ub1.webradio.proto.PacketProtos.internal_static_alpv_ws1112_ub1_webradio_proto_Message_fieldAccessorTable;
    }
    
    public interface ChatOrBuilder
        extends com.google.protobuf.MessageOrBuilder {
      
      // repeated string username = 1;
      java.util.List<String> getUsernameList();
      int getUsernameCount();
      String getUsername(int index);
      
      // repeated string message = 2;
      java.util.List<String> getMessageList();
      int getMessageCount();
      String getMessage(int index);
    }
    public static final class Chat extends
        com.google.protobuf.GeneratedMessage
        implements ChatOrBuilder {
      // Use Chat.newBuilder() to construct.
      private Chat(Builder builder) {
        super(builder);
      }
      private Chat(boolean noInit) {}
      
      private static final Chat defaultInstance;
      public static Chat getDefaultInstance() {
        return defaultInstance;
      }
      
      public Chat getDefaultInstanceForType() {
        return defaultInstance;
      }
      
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return alpv_ws1112.ub1.webradio.proto.PacketProtos.internal_static_alpv_ws1112_ub1_webradio_proto_Message_Chat_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return alpv_ws1112.ub1.webradio.proto.PacketProtos.internal_static_alpv_ws1112_ub1_webradio_proto_Message_Chat_fieldAccessorTable;
      }
      
      // repeated string username = 1;
      public static final int USERNAME_FIELD_NUMBER = 1;
      private com.google.protobuf.LazyStringList username_;
      public java.util.List<String>
          getUsernameList() {
        return username_;
      }
      public int getUsernameCount() {
        return username_.size();
      }
      public String getUsername(int index) {
        return username_.get(index);
      }
      
      // repeated string message = 2;
      public static final int MESSAGE_FIELD_NUMBER = 2;
      private com.google.protobuf.LazyStringList message_;
      public java.util.List<String>
          getMessageList() {
        return message_;
      }
      public int getMessageCount() {
        return message_.size();
      }
      public String getMessage(int index) {
        return message_.get(index);
      }
      
      private void initFields() {
        username_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        message_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;
        
        memoizedIsInitialized = 1;
        return true;
      }
      
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        for (int i = 0; i < username_.size(); i++) {
          output.writeBytes(1, username_.getByteString(i));
        }
        for (int i = 0; i < message_.size(); i++) {
          output.writeBytes(2, message_.getByteString(i));
        }
        getUnknownFields().writeTo(output);
      }
      
      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
      
        size = 0;
        {
          int dataSize = 0;
          for (int i = 0; i < username_.size(); i++) {
            dataSize += com.google.protobuf.CodedOutputStream
              .computeBytesSizeNoTag(username_.getByteString(i));
          }
          size += dataSize;
          size += 1 * getUsernameList().size();
        }
        {
          int dataSize = 0;
          for (int i = 0; i < message_.size(); i++) {
            dataSize += com.google.protobuf.CodedOutputStream
              .computeBytesSizeNoTag(message_.getByteString(i));
          }
          size += dataSize;
          size += 1 * getMessageList().size();
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }
      
      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }
      
      public static alpv_ws1112.ub1.webradio.proto.PacketProtos.Message.Chat parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static alpv_ws1112.ub1.webradio.proto.PacketProtos.Message.Chat parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static alpv_ws1112.ub1.webradio.proto.PacketProtos.Message.Chat parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static alpv_ws1112.ub1.webradio.proto.PacketProtos.Message.Chat parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static alpv_ws1112.ub1.webradio.proto.PacketProtos.Message.Chat parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static alpv_ws1112.ub1.webradio.proto.PacketProtos.Message.Chat parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static alpv_ws1112.ub1.webradio.proto.PacketProtos.Message.Chat parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static alpv_ws1112.ub1.webradio.proto.PacketProtos.Message.Chat parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static alpv_ws1112.ub1.webradio.proto.PacketProtos.Message.Chat parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static alpv_ws1112.ub1.webradio.proto.PacketProtos.Message.Chat parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      
      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(alpv_ws1112.ub1.webradio.proto.PacketProtos.Message.Chat prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }
      
      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements alpv_ws1112.ub1.webradio.proto.PacketProtos.Message.ChatOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return alpv_ws1112.ub1.webradio.proto.PacketProtos.internal_static_alpv_ws1112_ub1_webradio_proto_Message_Chat_descriptor;
        }
        
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return alpv_ws1112.ub1.webradio.proto.PacketProtos.internal_static_alpv_ws1112_ub1_webradio_proto_Message_Chat_fieldAccessorTable;
        }
        
        // Construct using alpv_ws1112.ub1.webradio.proto.PacketProtos.Message.Chat.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }
        
        private Builder(BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }
        
        public Builder clear() {
          super.clear();
          username_ = com.google.protobuf.LazyStringArrayList.EMPTY;
          bitField0_ = (bitField0_ & ~0x00000001);
          message_ = com.google.protobuf.LazyStringArrayList.EMPTY;
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }
        
        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }
        
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return alpv_ws1112.ub1.webradio.proto.PacketProtos.Message.Chat.getDescriptor();
        }
        
        public alpv_ws1112.ub1.webradio.proto.PacketProtos.Message.Chat getDefaultInstanceForType() {
          return alpv_ws1112.ub1.webradio.proto.PacketProtos.Message.Chat.getDefaultInstance();
        }
        
        public alpv_ws1112.ub1.webradio.proto.PacketProtos.Message.Chat build() {
          alpv_ws1112.ub1.webradio.proto.PacketProtos.Message.Chat result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }
        
        private alpv_ws1112.ub1.webradio.proto.PacketProtos.Message.Chat buildParsed()
            throws com.google.protobuf.InvalidProtocolBufferException {
          alpv_ws1112.ub1.webradio.proto.PacketProtos.Message.Chat result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(
              result).asInvalidProtocolBufferException();
          }
          return result;
        }
        
        public alpv_ws1112.ub1.webradio.proto.PacketProtos.Message.Chat buildPartial() {
          alpv_ws1112.ub1.webradio.proto.PacketProtos.Message.Chat result = new alpv_ws1112.ub1.webradio.proto.PacketProtos.Message.Chat(this);
          int from_bitField0_ = bitField0_;
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            username_ = new com.google.protobuf.UnmodifiableLazyStringList(
                username_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.username_ = username_;
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            message_ = new com.google.protobuf.UnmodifiableLazyStringList(
                message_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.message_ = message_;
          onBuilt();
          return result;
        }
        
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof alpv_ws1112.ub1.webradio.proto.PacketProtos.Message.Chat) {
            return mergeFrom((alpv_ws1112.ub1.webradio.proto.PacketProtos.Message.Chat)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }
        
        public Builder mergeFrom(alpv_ws1112.ub1.webradio.proto.PacketProtos.Message.Chat other) {
          if (other == alpv_ws1112.ub1.webradio.proto.PacketProtos.Message.Chat.getDefaultInstance()) return this;
          if (!other.username_.isEmpty()) {
            if (username_.isEmpty()) {
              username_ = other.username_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureUsernameIsMutable();
              username_.addAll(other.username_);
            }
            onChanged();
          }
          if (!other.message_.isEmpty()) {
            if (message_.isEmpty()) {
              message_ = other.message_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureMessageIsMutable();
              message_.addAll(other.message_);
            }
            onChanged();
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }
        
        public final boolean isInitialized() {
          return true;
        }
        
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder(
              this.getUnknownFields());
          while (true) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  this.setUnknownFields(unknownFields.build());
                  onChanged();
                  return this;
                }
                break;
              }
              case 10: {
                ensureUsernameIsMutable();
                username_.add(input.readBytes());
                break;
              }
              case 18: {
                ensureMessageIsMutable();
                message_.add(input.readBytes());
                break;
              }
            }
          }
        }
        
        private int bitField0_;
        
        // repeated string username = 1;
        private com.google.protobuf.LazyStringList username_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        private void ensureUsernameIsMutable() {
          if (!((bitField0_ & 0x00000001) == 0x00000001)) {
            username_ = new com.google.protobuf.LazyStringArrayList(username_);
            bitField0_ |= 0x00000001;
           }
        }
        public java.util.List<String>
            getUsernameList() {
          return java.util.Collections.unmodifiableList(username_);
        }
        public int getUsernameCount() {
          return username_.size();
        }
        public String getUsername(int index) {
          return username_.get(index);
        }
        public Builder setUsername(
            int index, String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  ensureUsernameIsMutable();
          username_.set(index, value);
          onChanged();
          return this;
        }
        public Builder addUsername(String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  ensureUsernameIsMutable();
          username_.add(value);
          onChanged();
          return this;
        }
        public Builder addAllUsername(
            java.lang.Iterable<String> values) {
          ensureUsernameIsMutable();
          super.addAll(values, username_);
          onChanged();
          return this;
        }
        public Builder clearUsername() {
          username_ = com.google.protobuf.LazyStringArrayList.EMPTY;
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
          return this;
        }
        void addUsername(com.google.protobuf.ByteString value) {
          ensureUsernameIsMutable();
          username_.add(value);
          onChanged();
        }
        
        // repeated string message = 2;
        private com.google.protobuf.LazyStringList message_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        private void ensureMessageIsMutable() {
          if (!((bitField0_ & 0x00000002) == 0x00000002)) {
            message_ = new com.google.protobuf.LazyStringArrayList(message_);
            bitField0_ |= 0x00000002;
           }
        }
        public java.util.List<String>
            getMessageList() {
          return java.util.Collections.unmodifiableList(message_);
        }
        public int getMessageCount() {
          return message_.size();
        }
        public String getMessage(int index) {
          return message_.get(index);
        }
        public Builder setMessage(
            int index, String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  ensureMessageIsMutable();
          message_.set(index, value);
          onChanged();
          return this;
        }
        public Builder addMessage(String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  ensureMessageIsMutable();
          message_.add(value);
          onChanged();
          return this;
        }
        public Builder addAllMessage(
            java.lang.Iterable<String> values) {
          ensureMessageIsMutable();
          super.addAll(values, message_);
          onChanged();
          return this;
        }
        public Builder clearMessage() {
          message_ = com.google.protobuf.LazyStringArrayList.EMPTY;
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
          return this;
        }
        void addMessage(com.google.protobuf.ByteString value) {
          ensureMessageIsMutable();
          message_.add(value);
          onChanged();
        }
        
        // @@protoc_insertion_point(builder_scope:alpv_ws1112.ub1.webradio.proto.Message.Chat)
      }
      
      static {
        defaultInstance = new Chat(true);
        defaultInstance.initFields();
      }
      
      // @@protoc_insertion_point(class_scope:alpv_ws1112.ub1.webradio.proto.Message.Chat)
    }
    
    private int bitField0_;
    // optional .alpv_ws1112.ub1.webradio.proto.Message.Chat chat = 1;
    public static final int CHAT_FIELD_NUMBER = 1;
    private alpv_ws1112.ub1.webradio.proto.PacketProtos.Message.Chat chat_;
    public boolean hasChat() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public alpv_ws1112.ub1.webradio.proto.PacketProtos.Message.Chat getChat() {
      return chat_;
    }
    public alpv_ws1112.ub1.webradio.proto.PacketProtos.Message.ChatOrBuilder getChatOrBuilder() {
      return chat_;
    }
    
    // optional string format = 2;
    public static final int FORMAT_FIELD_NUMBER = 2;
    private java.lang.Object format_;
    public boolean hasFormat() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getFormat() {
      java.lang.Object ref = format_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          format_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getFormatBytes() {
      java.lang.Object ref = format_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        format_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional bytes data = 3;
    public static final int DATA_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString data_;
    public boolean hasData() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public com.google.protobuf.ByteString getData() {
      return data_;
    }
    
    private void initFields() {
      chat_ = alpv_ws1112.ub1.webradio.proto.PacketProtos.Message.Chat.getDefaultInstance();
      format_ = "";
      data_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, chat_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getFormatBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, data_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, chat_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getFormatBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, data_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static alpv_ws1112.ub1.webradio.proto.PacketProtos.Message parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static alpv_ws1112.ub1.webradio.proto.PacketProtos.Message parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static alpv_ws1112.ub1.webradio.proto.PacketProtos.Message parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static alpv_ws1112.ub1.webradio.proto.PacketProtos.Message parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static alpv_ws1112.ub1.webradio.proto.PacketProtos.Message parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static alpv_ws1112.ub1.webradio.proto.PacketProtos.Message parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static alpv_ws1112.ub1.webradio.proto.PacketProtos.Message parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static alpv_ws1112.ub1.webradio.proto.PacketProtos.Message parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static alpv_ws1112.ub1.webradio.proto.PacketProtos.Message parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static alpv_ws1112.ub1.webradio.proto.PacketProtos.Message parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(alpv_ws1112.ub1.webradio.proto.PacketProtos.Message prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements alpv_ws1112.ub1.webradio.proto.PacketProtos.MessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return alpv_ws1112.ub1.webradio.proto.PacketProtos.internal_static_alpv_ws1112_ub1_webradio_proto_Message_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return alpv_ws1112.ub1.webradio.proto.PacketProtos.internal_static_alpv_ws1112_ub1_webradio_proto_Message_fieldAccessorTable;
      }
      
      // Construct using alpv_ws1112.ub1.webradio.proto.PacketProtos.Message.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getChatFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (chatBuilder_ == null) {
          chat_ = alpv_ws1112.ub1.webradio.proto.PacketProtos.Message.Chat.getDefaultInstance();
        } else {
          chatBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        format_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        data_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return alpv_ws1112.ub1.webradio.proto.PacketProtos.Message.getDescriptor();
      }
      
      public alpv_ws1112.ub1.webradio.proto.PacketProtos.Message getDefaultInstanceForType() {
        return alpv_ws1112.ub1.webradio.proto.PacketProtos.Message.getDefaultInstance();
      }
      
      public alpv_ws1112.ub1.webradio.proto.PacketProtos.Message build() {
        alpv_ws1112.ub1.webradio.proto.PacketProtos.Message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private alpv_ws1112.ub1.webradio.proto.PacketProtos.Message buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        alpv_ws1112.ub1.webradio.proto.PacketProtos.Message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public alpv_ws1112.ub1.webradio.proto.PacketProtos.Message buildPartial() {
        alpv_ws1112.ub1.webradio.proto.PacketProtos.Message result = new alpv_ws1112.ub1.webradio.proto.PacketProtos.Message(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (chatBuilder_ == null) {
          result.chat_ = chat_;
        } else {
          result.chat_ = chatBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.format_ = format_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.data_ = data_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof alpv_ws1112.ub1.webradio.proto.PacketProtos.Message) {
          return mergeFrom((alpv_ws1112.ub1.webradio.proto.PacketProtos.Message)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(alpv_ws1112.ub1.webradio.proto.PacketProtos.Message other) {
        if (other == alpv_ws1112.ub1.webradio.proto.PacketProtos.Message.getDefaultInstance()) return this;
        if (other.hasChat()) {
          mergeChat(other.getChat());
        }
        if (other.hasFormat()) {
          setFormat(other.getFormat());
        }
        if (other.hasData()) {
          setData(other.getData());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              alpv_ws1112.ub1.webradio.proto.PacketProtos.Message.Chat.Builder subBuilder = alpv_ws1112.ub1.webradio.proto.PacketProtos.Message.Chat.newBuilder();
              if (hasChat()) {
                subBuilder.mergeFrom(getChat());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setChat(subBuilder.buildPartial());
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              format_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              data_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional .alpv_ws1112.ub1.webradio.proto.Message.Chat chat = 1;
      private alpv_ws1112.ub1.webradio.proto.PacketProtos.Message.Chat chat_ = alpv_ws1112.ub1.webradio.proto.PacketProtos.Message.Chat.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          alpv_ws1112.ub1.webradio.proto.PacketProtos.Message.Chat, alpv_ws1112.ub1.webradio.proto.PacketProtos.Message.Chat.Builder, alpv_ws1112.ub1.webradio.proto.PacketProtos.Message.ChatOrBuilder> chatBuilder_;
      public boolean hasChat() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public alpv_ws1112.ub1.webradio.proto.PacketProtos.Message.Chat getChat() {
        if (chatBuilder_ == null) {
          return chat_;
        } else {
          return chatBuilder_.getMessage();
        }
      }
      public Builder setChat(alpv_ws1112.ub1.webradio.proto.PacketProtos.Message.Chat value) {
        if (chatBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          chat_ = value;
          onChanged();
        } else {
          chatBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder setChat(
          alpv_ws1112.ub1.webradio.proto.PacketProtos.Message.Chat.Builder builderForValue) {
        if (chatBuilder_ == null) {
          chat_ = builderForValue.build();
          onChanged();
        } else {
          chatBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder mergeChat(alpv_ws1112.ub1.webradio.proto.PacketProtos.Message.Chat value) {
        if (chatBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              chat_ != alpv_ws1112.ub1.webradio.proto.PacketProtos.Message.Chat.getDefaultInstance()) {
            chat_ =
              alpv_ws1112.ub1.webradio.proto.PacketProtos.Message.Chat.newBuilder(chat_).mergeFrom(value).buildPartial();
          } else {
            chat_ = value;
          }
          onChanged();
        } else {
          chatBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder clearChat() {
        if (chatBuilder_ == null) {
          chat_ = alpv_ws1112.ub1.webradio.proto.PacketProtos.Message.Chat.getDefaultInstance();
          onChanged();
        } else {
          chatBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      public alpv_ws1112.ub1.webradio.proto.PacketProtos.Message.Chat.Builder getChatBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getChatFieldBuilder().getBuilder();
      }
      public alpv_ws1112.ub1.webradio.proto.PacketProtos.Message.ChatOrBuilder getChatOrBuilder() {
        if (chatBuilder_ != null) {
          return chatBuilder_.getMessageOrBuilder();
        } else {
          return chat_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          alpv_ws1112.ub1.webradio.proto.PacketProtos.Message.Chat, alpv_ws1112.ub1.webradio.proto.PacketProtos.Message.Chat.Builder, alpv_ws1112.ub1.webradio.proto.PacketProtos.Message.ChatOrBuilder> 
          getChatFieldBuilder() {
        if (chatBuilder_ == null) {
          chatBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              alpv_ws1112.ub1.webradio.proto.PacketProtos.Message.Chat, alpv_ws1112.ub1.webradio.proto.PacketProtos.Message.Chat.Builder, alpv_ws1112.ub1.webradio.proto.PacketProtos.Message.ChatOrBuilder>(
                  chat_,
                  getParentForChildren(),
                  isClean());
          chat_ = null;
        }
        return chatBuilder_;
      }
      
      // optional string format = 2;
      private java.lang.Object format_ = "";
      public boolean hasFormat() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getFormat() {
        java.lang.Object ref = format_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          format_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setFormat(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        format_ = value;
        onChanged();
        return this;
      }
      public Builder clearFormat() {
        bitField0_ = (bitField0_ & ~0x00000002);
        format_ = getDefaultInstance().getFormat();
        onChanged();
        return this;
      }
      void setFormat(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        format_ = value;
        onChanged();
      }
      
      // optional bytes data = 3;
      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasData() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        data_ = value;
        onChanged();
        return this;
      }
      public Builder clearData() {
        bitField0_ = (bitField0_ & ~0x00000004);
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:alpv_ws1112.ub1.webradio.proto.Message)
    }
    
    static {
      defaultInstance = new Message(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:alpv_ws1112.ub1.webradio.proto.Message)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_alpv_ws1112_ub1_webradio_proto_Message_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_alpv_ws1112_ub1_webradio_proto_Message_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_alpv_ws1112_ub1_webradio_proto_Message_Chat_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_alpv_ws1112_ub1_webradio_proto_Message_Chat_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n1alpv_ws1112/ub1/webradio/proto/packetp" +
      "rotos.proto\022\036alpv_ws1112.ub1.webradio.pr" +
      "oto\"\216\001\n\007Message\022:\n\004chat\030\001 \001(\0132,.alpv_ws1" +
      "112.ub1.webradio.proto.Message.Chat\022\016\n\006f" +
      "ormat\030\002 \001(\t\022\014\n\004data\030\003 \001(\014\032)\n\004Chat\022\020\n\010use" +
      "rname\030\001 \003(\t\022\017\n\007message\030\002 \003(\tB.\n\036alpv_ws1" +
      "112.ub1.webradio.protoB\014PacketProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_alpv_ws1112_ub1_webradio_proto_Message_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_alpv_ws1112_ub1_webradio_proto_Message_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_alpv_ws1112_ub1_webradio_proto_Message_descriptor,
              new java.lang.String[] { "Chat", "Format", "Data", },
              alpv_ws1112.ub1.webradio.proto.PacketProtos.Message.class,
              alpv_ws1112.ub1.webradio.proto.PacketProtos.Message.Builder.class);
          internal_static_alpv_ws1112_ub1_webradio_proto_Message_Chat_descriptor =
            internal_static_alpv_ws1112_ub1_webradio_proto_Message_descriptor.getNestedTypes().get(0);
          internal_static_alpv_ws1112_ub1_webradio_proto_Message_Chat_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_alpv_ws1112_ub1_webradio_proto_Message_Chat_descriptor,
              new java.lang.String[] { "Username", "Message", },
              alpv_ws1112.ub1.webradio.proto.PacketProtos.Message.Chat.class,
              alpv_ws1112.ub1.webradio.proto.PacketProtos.Message.Chat.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
